### ISSUE TITLE
Handle authentication for initial registration

### ISSUE THREAD

**Issue by binukjose** [nabinthomas/amazert#3]
Problem.
1. If a hacker comes with "generated uid" can he create an additional "generated id" ?
  Even if  and he is already authenticated as 

Sub steps
2. Login --> You will get a UID 
3. Clean db, hack the UID and send the request to register a device .

**Comment by spanakkal** [comment]
Validated this case by adding the first entry of a user using a modified UID field.
Tried 2 cases :
1. Reused and existing UID from the DB - 
[ W/RepoOperation: setValue at /WhqYuV1HZZbCroLpqBX5k22W3jk1/device/device-WhqYuV1HZZbCroLpqBX5k22W3jk1 failed: DatabaseError: Permission denied ] 

2. Tried using a random string as UID: 
[ W/RepoOperation: setValue at /asdfgtreqwertrewedfd/device/device-asdfgtreqwertrewedfd failed: DatabaseError: Permission denied ] 

The firebase rules are kicking in both the cases and thus ensures that a malicious user can create a a fake entry ONLY by being able to authenticate as the user [ which is out of SW control].
